### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by danielkmetz** [aptmac/draftaid-react#15]
After installing all the requirements I am receiving the following error. 

C:\draftaid-react-main>bash run.sh
run.sh: line 3: python: command not found
run.sh: line 4: python: command not found
run.sh: line 6: npm: command not found
run.sh: line 7: npm: command not found
run.sh: line 8: npm: command not found

I do have python and npm installed on my system.

**Comment by aptmac** [comment]
Hey! What OS are you on, and what's the output of:

1. `python --version`

2. `npm -v`

And do you have npm and python added to your path?

Lastly, at least for the python scripts, you could try removing the shebang lines [0][1], maybe that's what's causing your computer to look in the wrong spot for python.

[0] https://github.com/aptmac/draftaid-react/blob/main/data/fetch_beersheets.py#L1
[1] https://github.com/aptmac/draftaid-react/blob/main/data/fetch_fp.py#L1

**Comment by danielkmetz** [comment]
Hey! thanks for the fast response. I am on Windows 10, and the following outputs are what I'm getting

python 3.8.1

C:\Users\daniel.kmetz>npm -v
'npm' is not recognized as an internal or external command,
operable program or batch file.

Which is interesting since I can see that I have downloaded it.

**Comment by aptmac** [comment]
> Hey! thanks for the fast response. I am on Windows 10, and the following outputs are what I'm getting
> 
> python 3.8.1

Nice, okay then I'd suggest maybe trying without the shebang lines, maybe that interferes with running python.

> C:\Users\daniel.kmetz>npm -v
> 'npm' is not recognized as an internal or external command,
> operable program or batch file.
> 
> Which is interesting since I can see that I have downloaded it.

Alrighty, looks like you'll just have to add it to your path. When you install nodejs there should be an option in the installer to also set up the paths ([example](https://stackoverflow.com/a/42731621)), otherwise there's an example [here](https://stackoverflow.com/a/27344046) that goes over it.

**Comment by danielkmetz** [comment]
I did not see that nodejs was a required download!

**Comment by aptmac** [comment]
Ah, I should maybe note that somewhere. You can't really use npm without node, (npm is nodejs package manager), so I guess it'd be like having pip but no python hah.

**Comment by danielkmetz** [comment]
I got it to work! You're awesome thanks for your help. Does this not connect to espn to give me a live dashboard during my live draft?

**Comment by aptmac** [comment]
Sweet! Unfortunately not, this is a standalone bare-bones app. The idea is that you have it running on a second monitor (or split screen) and just tick off players as they get drafted in your real draft.

I'm not sure if espn has an api to track the draft, or if it'd be easier to scrape the page as you go draft, but that would be a nifty idea for a new feature. I'm personally on Yahoo, and I know Sleeper is getting popular as well, this could evolve into a pretty neat feature if it could be setup across all the major platforms.

I'll close this issue now, if anything pops up in the future feel free to comment back here or open a new issue.
